export const TECHNIQUES_LIST = [
  "Air Squat", "Front Squat", "Overhead Squat", "Lunge", "Reverse Lunge", "Walking Lunge", "Jumping Lunge", "Box Step-Up", "Box Jump", "Box Jump Over", "Burpee", "Burpee Box Jump", "Burpee Box Jump Over", "Push-Up", "Hand Release Push-Up", "Ring Row", "Strict Pull-Up", "Kipping Pull-Up", "Butterfly Pull-Up", "Chest to Bar Pull-Up", "Bar Muscle-Up", "Ring Muscle-Up", "Toes to Bar", "Knees to Elbows", "Hanging Knee Raise", "Sit-Up", "AbMat Sit-Up", "V-Up", "Hollow Rock", "Hollow Hold", "Arch Hold", "Superman Hold", "Plank", "Side Plank",
  "Wall Walk", "Handstand Hold", "Handstand Push-Up", "Strict Handstand Push-Up", "Kipping Handstand Push-Up", "Deficit Handstand Push-Up", "Handstand Walk", "Handstand Shoulder Tap", "Handstand Box Hold", "Wall Facing Handstand Hold", "Bear Crawl", "Crab Walk",
  "Ring Support Hold", "Ring Dip", "Strict Ring Dip", "Kipping Ring Dip", "Ring Row", "Ring Muscle-Up", "Ring Transition Drill", "Skin the Cat", "L-Sit Rings",
  "Snatch Deadlift", "Snatch Pull", "Snatch High Pull", "Muscle Snatch", "Power Snatch", "Squat Snatch", "Hang Power Snatch", "Hang Squat Snatch", "High Hang Snatch", "Tall Snatch", "Snatch Balance", "Heaving Snatch Balance", "Drop Snatch", "Snatch Push Press", "Behind the Neck Snatch Push Press", "Snatch Grip Deadlift", "Snatch Grip Romanian Deadlift", "Pause Snatch", "Tempo Snatch",
  "Clean Deadlift", "Clean Pull", "Clean High Pull", "Muscle Clean", "Power Clean", "Squat Clean", "Hang Power Clean", "Hang Squat Clean", "High Hang Clean", "Tall Clean", "Clean Grip Deadlift", "Clean Grip Romanian Deadlift", "Pause Clean", "Tempo Clean",
  "Strict Press", "Push Press", "Push Jerk", "Split Jerk", "Power Jerk", "Behind the Neck Jerk", "Jerk Balance", "Tall Jerk", "Jerk Dip", "Jerk Drive", "Pause Jerk", "Tempo Jerk",
  "Clean + Front Squat + Jerk", "Power Clean + Hang Clean", "Snatch Pull + Snatch", "Clean Pull + Clean", "Snatch + Overhead Squat", "Power Snatch + Overhead Squat", "Power Clean + Front Squat + Jerk",
  "Back Squat", "Front Squat", "Overhead Squat", "Deadlift", "Sumo Deadlift", "Romanian Deadlift", "Stiff Leg Deadlift", "Bench Press", "Floor Press", "Good Morning", "Hip Thrust", "Glute Bridge", "Zercher Squat", "Bulgarian Split Squat",
  "Run", "Sprint", "Shuttle Run", "Row", "Sprint Row", "Bike", "Echo Bike", "Assault Bike", "Bike Erg", "Ski Erg", "Single Under", "Double Under", "Crossover", "Double Under Crossover",
  "Dumbbell Deadlift", "Dumbbell Hang Clean", "Dumbbell Power Clean", "Dumbbell Squat Clean", "Dumbbell Snatch", "Alternating Dumbbell Snatch", "Dumbbell Thruster", "Dumbbell Push Press", "Dumbbell Push Jerk", "Dumbbell Split Jerk", "Dumbbell Front Squat", "Dumbbell Overhead Squat", "Dumbbell Lunge", "Dumbbell Step-Up", "Dumbbell Bench Press", "Dumbbell Renegade Row", "Devil Press", "Man Maker",
  "Kettlebell Deadlift", "Kettlebell Swing Russian", "Kettlebell Swing American", "Kettlebell Clean", "Kettlebell Snatch", "Kettlebell Push Press", "Kettlebell Jerk", "Kettlebell Goblet Squat", "Kettlebell Windmill", "Turkish Get Up", "Bottom Up Press",
  "Farmer Carry", "Suitcase Carry", "Front Rack Carry", "Overhead Carry", "Sandbag Carry", "Sandbag Clean", "Sandbag to Shoulder", "Sandbag Over Shoulder", "Sandbag Squat", "Yoke Carry", "Sled Push", "Sled Pull", "Tire Flip", "Med Ball Carry", "Husafell Carry", "Waiter Carry",
  "Wall Ball", "Wall Ball Shot", "Med Ball Clean", "Med Ball Squat Clean", "Med Ball Sit-Up Throw", "Slam Ball", "Rotational Throw", "Chest Pass",
  "Tall Snatch", "Tall Clean", "Snatch High Hang", "Clean High Hang", "Jerk Footwork", "Dip and Drive Drill", "Snatch Receiving Drill", "Clean Receiving Drill", "Kip Swing", "Beat Swing", "Hollow to Arch Drill", "Pull Up Kip Drill", "Toes to Bar Kip Drill", "Handstand Kick Up", "Row Catch Drill", "Row Finish Drill", "Jump Rope Timing Drill",
  "PVC Pass Through", "Shoulder Dislocates", "Snatch Grip Press", "Sotts Press", "Press in Snatch", "Press in Split", "Ankle Mobility Drill", "Hip Opener Drill", "Thoracic Rotation Drill", "Couch Stretch", "Front Rack Mobility", "Overhead Mobility", "Scap Pull Up", "Scap Push Up", "Banded Face Pull", "Banded Lat Activation", "Glute Activation Drill"
];

export const UNIQUE_TECHNIQUES = Array.from(new Set(TECHNIQUES_LIST));
